
//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Sat Oct 11 19:18:20 CDT 2025
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int SHORT = 14;
  static final int SIGNED = 81;
  static final int TIMES = 45;
  static final int GT = 50;
  static final int ARROW = 70;
  static final int DIVASSIGN = 41;
  static final int CONST = 18;
  static final int GE = 51;
  static final int PERIOD = 36;
  static final int REGISTER = 80;
  static final int ENUM = 75;
  static final int SIZEOF = 82;
  static final int RBRACK = 29;
  static final int COMMA = 33;
  static final int RBRACE = 31;
  static final int RPAREN = 27;
  static final int LBRACK = 28;
  static final int LT = 48;
  static final int INCREMENT = 57;
  static final int SUBASSIGN = 39;
  static final int DOUBLE = 79;
  static final int STRUCT = 83;
  static final int LBRACE = 30;
  static final int BWISEANDASSIGN = 65;
  static final int LPAREN = 26;
  static final int MODASSIGN = 42;
  static final int NOT = 56;
  static final int TILDE = 62;
  static final int LE = 49;
  static final int VAR = 2;
  static final int FLOAT = 78;
  static final int BITWISEAND = 59;
  static final int GOTO = 76;
  static final int EQ = 52;
  static final int LSHIFTASSIGN = 68;
  static final int MODULUS = 47;
  static final int LONG = 77;
  static final int PLUS = 43;
  static final int DIVIDE = 46;
  static final int QUESTION = 34;
  static final int UNION = 86;
  static final int WHILE = 7;
  static final int OCTAL_LITERAL = 23;
  static final int ASSIGN = 37;
  static final int CHAR = 13;
  static final int ADDASSIGN = 38;
  static final int SWITCH = 84;
  static final int DO = 8;
  static final int FOR = 6;
  static final int VOID = 15;
  static final int EXTERN = 16;
  static final int RETURN = 9;
  static final int ELSE = 5;
  static final int BREAK = 10;
  static final int FUN = 3;
  static final int INT = 12;
  static final int STRING_LITERAL = 25;
  static final int EOF = 0;
  static final int SEMICOLON = 32;
  static final int DEFAULT = 74;
  static final int ELIPSES = 71;
  static final int MULASSIGN = 40;
  static final int DECREMENT = 58;
  static final int MINUS = 44;
  static final int OR = 55;
  static final int error = 1;
  static final int DECIMAL_LITERAL = 21;
  static final int CONTINUE = 11;
  static final int IF = 4;
  static final int UNSIGNED = 87;
  static final int BWISEOR = 60;
  static final int ID = 20;
  static final int COLON = 35;
  static final int BWISEXOR = 61;
  static final int HEX_LITERAL = 22;
  static final int BWISEORASSIGN = 66;
  static final int RSHIFTASSIGN = 69;
  static final int VOLATILE = 17;
  static final int CHAR_LITERAL = 24;
  static final int CASE = 73;
  static final int RSHIFT = 64;
  static final int BWISEXORASSIGN = 67;
  static final int NEQ = 53;
  static final int AND = 54;
  static final int STATIC = 19;
  static final int LSHIFT = 63;
  static final int TYPEDEF = 85;
  static final int AUTO = 72;

  /* non terminals */
  static final int program = 1;
  static final int bitfield_list = 4;
  static final int struct_declaration_list = 26;
  static final int initializer = 30;
  static final int pointer_list = 9;
  static final int array_suffixes = 15;
  static final int enumerator = 28;
  static final int $START = 0;
  static final int param = 19;
  static final int initializer_list = 29;
  static final int param_list_opt = 17;
  static final int struct_or_union = 24;
  static final int name = 38;
  static final int init_opt = 37;
  static final int compound_stmt = 33;
  static final int expression_array_type_list = 13;
  static final int param_list = 18;
  static final int exp_list = 36;
  static final int bitfield_value = 5;
  static final int enumerator_list = 27;
  static final int parameter_type_list = 23;
  static final int type_parameters = 20;
  static final int empty_array_type_list = 11;
  static final int brackets_list = 10;
  static final int type_name = 7;
  static final int exp_or_decl_opt = 39;
  static final int array_suffix = 16;
  static final int stmt_list = 32;
  static final int empty_array_type = 12;
  static final int parameter_list = 22;
  static final int expression_array_type = 14;
  static final int type_augments = 8;
  static final int comma_exp = 35;
  static final int parameters = 21;
  static final int struct_or_union_declarator = 25;
  static final int exp_opt = 40;
  static final int decl = 3;
  static final int decl_list = 2;
  static final int exp = 34;
  static final int stmt = 31;
  static final int type = 6;
}

